name: base
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anaconda-anon-usage=0.5.0
  - annotated-types=0.6.0
  - archspec=0.2.3
  - attr=2.5.1
  - blosc=1.21.5
  - boltons=24.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.4.26
  - certifi=2025.4.26
  - cffi=1.17.1
  - cftime=1.6.4
  - charset-normalizer=3.3.2
  - conda=25.5.0
  - conda-anaconda-telemetry=0.1.2
  - conda-anaconda-tos=0.1.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=25.1.1
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - cpp-expected=1.1.0
  - cryptography=43.0.3
  - distro=1.9.0
  - esmf=8.8.1
  - esmpy=8.8.1
  - expat=2.6.4
  - fmt=9.1.0
  - frozendict=2.4.2
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=73.1
  - idna=3.7
  - jsonpatch=1.33
  - jsonpointer=2.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libaec=1.1.3
  - libarchive=3.7.7
  - libblas=3.9.0
  - libcap=2.71
  - libcblas=3.9.0
  - libcurl=8.11.1
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.4
  - libfabric=2.1.0
  - libfabric1=2.1.0
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libhwloc=2.11.2
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libmamba=2.0.5
  - libmambapy=2.0.5
  - libnetcdf=4.9.2
  - libnghttp2=1.57.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libpnetcdf=1.13.0
  - libsolv=0.7.30
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=256.9
  - libudev1=257.4
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libzip=1.10.1
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - mdurl=0.1.0
  - menuinst=2.2.0
  - mpi=1.0.1
  - mpich=4.3.0
  - ncurses=6.4
  - netcdf-fortran=4.6.1
  - netcdf4=1.6.5
  - nlohmann_json=3.11.2
  - numpy=2.2.6
  - openssl=3.5.0
  - packaging=24.2
  - parallelio=2.6.3
  - pcre2=10.42
  - pip=25.0
  - platformdirs=3.10.0
  - pluggy=1.5.0
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.12.2
  - python_abi=3.12
  - rdma-core=55.0
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.3
  - rich=13.9.4
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - setuptools=75.8.0
  - simdjson=3.10.1
  - snappy=1.2.1
  - spdlog=1.11.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tqdm=4.67.1
  - truststore=0.10.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - ucx=1.18.0
  - urllib3=2.3.0
  - wheel=0.45.1
  - xz=5.4.6
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - affine==2.4.0
      - attrs==25.3.0
      - cf-xarray==0.10.5
      - click==8.2.1
      - click-plugins==1.1.1
      - cligj==0.7.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.58.1
      - git-filter-repo==2.47.0
      - kiwisolver==1.4.8
      - llvmlite==0.44.0
      - matplotlib==3.10.3
      - numba==0.61.2
      - pandas==2.2.3
      - pillow==11.2.1
      - pyhdf==0.11.6
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - rasterio==1.4.3
      - shapely==2.1.1
      - six==1.17.0
      - sparse==0.17.0
      - tzdata==2025.2
      - xarray==2025.4.0
      - xesmf==0.8.10
